Added descriptive comments to DSPASpec
opendatahub-io/data-science-pipelines-operator pull request #360
Opened 2023-09-26 13:50 UTC by hbelmiro

## The issue resolved by this Pull Request:
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/200

## Description of your changes:
Added descriptive comments to DSPASpec

## Testing instructions

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-09-26 13:54 UTC, dsp-developers commented
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-360`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/360/head
git checkout -b pullrequest 1104d1815ea10e70695ad29da591ae36fe051b16
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-360"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

2023-09-27 19:14 UTC, HumairAK requested changes

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	InjectDefaultScript bool `json:"injectDefaultScript"`
"Inject the archive step script."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	EnableRoute bool `json:"enableOauth"`
"Create an Openshift Route for this DSP API Server."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	EnableSamplePipeline bool `json:"enableSamplePipeline"`
"Include sample pipelines with the deployment of this DSP API Server."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Image  string `json:"image,omitempty"`
"Specify a custom image for DSP PersistenceAgent."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Deploy bool   `json:"deploy"`
"Enable DS Pipelines Operator management of Persisence Agent. Setting Deploy to false disables operator reconciliation."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	NumWorkers int                   `json:"numWorkers,omitempty"`
"Number of worker for Persistence Agent sync job."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Resources  *ResourceRequirements `json:"resources,omitempty"`
"Specify custom Pod resource requirements for this component."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Resources            *ResourceRequirements `json:"resources,omitempty"`
"Specify custom Pod resource requirements for this component."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Resources *ResourceRequirements `json:"resources,omitempty"`
"Specify custom Pod resource requirements for this component."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Resources *ResourceRequirements `json:"resources,omitempty"`
"Specify custom Pod resource requirements for this component."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Deploy bool   `json:"deploy"`
"Enable DS Pipelines Operator management of ScheduledWorkflow. Setting Deploy to false disables operator reconciliation."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Image  string `json:"image,omitempty"`
"Specify a custom image for DSP ScheduledWorkflow controller."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	CronScheduleTimezone string                `json:"cronScheduleTimezone,omitempty"`
"Specify the Cron timezone used for ScheduledWorkflow PipelineRuns."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Deploy        bool                  `json:"deploy"`
"Enable DS Pipelines Operator management of KFP UI. Setting Deploy to false disables operator reconciliation."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Deploy bool   `json:"deploy"`
"Enable DS Pipelines Operator management of MariaDB. Setting Deploy to false disables operator reconciliation."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Deploy bool `json:"deploy"`
"Enable DS Pipelines Operator management of Minio. Setting Deploy to false disables operator reconciliation."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Deploy  bool `json:"deploy"`
"Enable DS Pipelines Operator management of MLMD. Setting Deploy to false disables operator reconciliation."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Image  string `json:"image,omitempty"`
"Specify a custom image for DSP MariaDB pod."

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Image  string `json:"image,omitempty"`
can you also add similar comments for the remaining "image" fields

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	PVCSize   resource.Quantity     `json:"pvcSize,omitempty"`
Customize the size of the PVC created for the default MariaDB instance.

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	PVCSize   resource.Quantity     `json:"pvcSize,omitempty"`
Customize the size of the PVC created for the Minio instance.

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Bucket              string `json:"bucket,omitempty"`
Provide the Bucket name that will be used to store artifacts in S3. If provided bucket does not exist, DSP Apiserver will attempt to create it. As such the credentials provided should have sufficient permissions to do create buckets.

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	*S3CredentialSecret `json:"s3CredentialsSecret,omitempty"`
Credentials for the S3 user (e.g. IAM user cred stored in a k8s secret.).
Note that the S3 user should have the permissions to create a bucket if the provided bucket does not exist.

2023-09-27 19:14 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
>  	Resources *ResourceRequirements `json:"resources,omitempty"`
can you add similar comments to all other `Resources` fields.

2023-09-28 19:58 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-360`

2023-09-28 19:59 UTC, hbelmiro commented
@HumairAK I incorporated your suggestions. Can you have a second look, please?

2023-10-03 13:59 UTC, HumairAK commented
@hbelmiro the `make manifests` command should not result in any diffs. Can you double check?

2023-10-03 15:10 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-360`

2023-10-04 13:58 UTC, HumairAK commented
/lgtm
/approve

Great work!

2023-10-04 14:02 UTC, merged