Parameterize CABundle mountpath in dspa
opendatahub-io/data-science-pipelines-operator pull request #607
Opened 2024-03-16 04:07 UTC by VaniHaripriya

## The issue resolved by this Pull Request:

Resolves [RHOAIENG-3780](https://issues.redhat.com/browse/RHOAIENG-3780)

## Description of your changes:

- Added new parameter for caBundleMountPath which can be set by users in dspa. 
- Overrides the values of default values of CustomCABundleRootMountPath and CustomCABundleRootMountPath , if the values are provided in dspa.

## Testing instructions

Deploy dspa using the below yaml file .Create a pipeline run and verify the mount paths in kfp-launcher pod to see the ca-bundle mountpath that we provided in the dspa.
```
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: sample
spec:
  dspVersion: v2
  apiServer:
    deploy: true
    enableSamplePipeline: true
    # If developing against a cluster using self-signed certs, then uncomment this field.
    cABundle:
      configMapName: kube-root-ca.crt
      configMapKey: ca.crt
      caBundleMountPath: /etc/ssl/certs
  objectStorage:
    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
  mlpipelineUI:
    image: quay.io/opendatahub/ds-pipelines-frontend:latest
```
## Checklist
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

2024-03-16 04:09 UTC, dsp-developers commented
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-607`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/607/head
git checkout -b pullrequest 93541825bc618473a534956b5f197cd89359b6a0
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-607"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

2024-03-20 17:47 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
> +	// +kubebuilder:validation:Required
add description, mention that this is where the ca bundle will be mounted in pipeline server and user executor pods

2024-03-21 17:28 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-607`

2024-03-21 21:25 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-607`

2024-03-22 13:29 UTC, HumairAK commented on api/v1alpha1/dspipeline_types.go
> +	CABundleFileMountPath string `json:"caBundleFileMountPath"`
@VaniHaripriya can you update this file also with this new field: https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/samples/v2/dspa-all-fields/dspa_all_fields.yaml 

this file is just an example to list all available crd fields, so you can put any example like: 

```yaml
caBundleFileMountPath:  /your/certbundle/path.crt
```

2024-03-22 13:59 UTC, HumairAK commented on controllers/dspipeline_params.go
> +		p.PiplinesCABundleMountPath = fmt.Sprintf("%s/%s", p.CustomCABundleRootMountPath, dspTrustedCAConfigMapKey)
I think you have confused the user provided configmap with the one we create. 

User provides a configmap [here](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/api/v1alpha1/dspipeline_types.go#L77). We use this configmap (and another configmap "odh-trusted-ca-bundle" if provided), and combine them to create a new configmap [here](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/controllers/dspipeline_params.go#L646-L671). It's this 2nd configmap that we create, which we want to allow the user to _also_ control but this is unrelated to the configmap key provided via `p.APIServer.CABundle.ConfigMapKey`.  

`p.APIServer.CABundle` is the user saying "please create a new cabundle, but include my cabundle found at this specified location". 

`.spec.apiServer.CABundleFileName` is the user saying, "when you create this new cabundle, please put it in this folder". 

We want a new field that says, "when you create this new cabundle, please put it in this folder, and use **this filename**". 

For this we need to introduce a new crd `.spec.apiServer.CABundleFileName` with a description: 

> CABundleFileName is the name given to the CABundle created in the path CaBundleFileMountPath (default dspa.crt)

Use this to populate `dspTrustedCAConfigMapKey` much like you do `p.CustomCABundleRootMountPath`

2024-03-22 14:00 UTC, HumairAK commented on controllers/dspipeline_params.go
> +		p.PiplinesCABundleMountPath = fmt.Sprintf("%s/%s", p.CustomCABundleRootMountPath, dspTrustedCAConfigMapKey)
be sure to also add this new field to: https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/samples/v2/dspa-all-fields/dspa_all_fields.yaml

2024-03-22 19:46 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-607`

2024-03-25 16:49 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-607`

2024-04-08 15:09 UTC, HumairAK requested changes

2024-04-08 15:14 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-607`

2024-04-08 15:15 UTC, HumairAK commented
/lgtm
/approve

2024-04-08 15:17 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-607`

2024-04-08 15:25 UTC, merged